version: '3.8'

services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app  
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    ports:
      - "3001:3001"
    command: npm start start:dev 
    depends_on:
      - redis
      - postgres

  migrate-db:
    build:
      dockerfile: Dockerfile
      context: .
    links:
      - postgres
    command: npm run migrate:up

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  postgres:
    container_name: postgress
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
      
volumes:
  redis:
    driver: local
  docker-nest-postgres:  
